server:
  port: 8081
spring:
  application:
    name: booking_service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    tryItOutEnabled: true
resttemplate:
  url:
    customer: http://app-customers:8082/customers
    room: http://app-hotel:8083/hotels/rooms
    hotel: http://app-hotel:8083/hotels